// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserMetadata(ctx context.Context, arg CreateUserMetadataParams) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserMetadata(ctx context.Context, userID uuid.UUID) (UserMetadatum, error)
	GetUserWithMetadata(ctx context.Context, id uuid.UUID) (GetUserWithMetadataRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
